version: 2
jobs:
  build:
    working_directory: ~/openvas
    docker:
      - image: docker:17.03.0-ce
    steps:
      - run:
          name: Add deps
          command: |
            set -x
            apk --no-cache add openssh git bash --no-progress
      - checkout
      - setup_docker_engine
      - run: 9/ci.sh
      - store_artifacts:
          path: 9/logs
          destination: 9-logs
      - store_artifacts:
          path: 9/images
          destination: 9-images
